name: Test
on:
  push:
jobs:
  run-with-setup-node:
    name: Run with node 20 via actions/setup-node
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          eas-cache: false
  run-with-setup-node-18:
    name: Run with node 18 via actions/setup-node
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          eas-cache: false
  run-without-setup-node:
    name: Run default node 18
    runs-on: [ubuntu-latest]
    steps:
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          eas-cache: false